### ISSUE TITLE
sometimes get "charttype" not valid PP in DSP though doesnt seem to cause any problems - can we look into this?

### ISSUE THREAD

**Issue by mzummo** [hpcc-systems/Visualization#1147]

**Comment by mlzummo** [comment]
@GordonSmith 

seems to be caused by this being passed in: 

https://github.com/hpcc-systems/Visualization/blob/master/src/marshaller/HipieDDL.js#L672

to this:

https://github.com/hpcc-systems/Visualization/blob/master/src/chart/MultiChart.js#L146 (and this is being called on the widget inside the multichart not the multichart itself)

**Comment by mlzummo** [comment]
though im unsure as to why it doesnt happen everytime?

**Comment by GordonSmith** [comment]
@mlzummo can you provide steps to reproduce?

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
