### ISSUE TITLE
UI glitches in rendering table widget

### ISSUE THREAD

**Issue by RajalakshmiElumalaiCts** [hpcc-systems/Visualization#1162]
With 1.10.0 branch of Visualization library, Extra rows/columns added into table.

![column](https://cloud.githubusercontent.com/assets/5885849/10998260/eb62f6ae-84b9-11e5-8c6e-488c4294f056.jpg)
![row](https://cloud.githubusercontent.com/assets/5885849/10998261/eb64c182-84b9-11e5-920f-3f7ec667a7d6.jpg)

**Comment by dtsnell4** [comment]
Matt already reported this https://github.com/hpcc-systems/Visualization/issues/1143, and as noted it was already fixed in https://github.com/hpcc-systems/Visualization/pull/1104.  Just waiting for pull.

**Comment by dtsnell4** [comment]
Additionally, as I mentioned in https://github.com/hpcc-systems/Visualization/issues/1143, I am completely refactoring the table to remove all the slow copying code, and be 100% d3.  Going very well so far.   Additionally, all of the various features (fixed this and that, formatting, totals) have made the code difficult to manage since they were all created independently and are competing for the same elements.  The refactor will make it much more manageable and less bug-prone.
