### ISSUE TITLE
Avenger (AVP) needs to convert our charts to Image/PDF

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#1187]
@GordonSmith Do we have plans to support client-side conversion to image? And/or do we have a modular server-side solution?

**Comment by dabayliss** [comment]
Per Ken Foglia Raghu has the PDF conversion working

**Comment by GordonSmith** [comment]
Client side convert to image (and copy to clipboard) is a "nice to have" - server side PDF generation is the requirement (PhantomJS has a save as PDF option which is what is being used in the UK and since its what we use for our unit tests its known to work 100% and is performant etc.).  I don't believe there is any outstanding technical problem at this stage and its now a hosting / server service configuration issue.

**Comment by jbrundage** [comment]
@GordonSmith Are you saying we'll eventually have a hosted service that can convert widgets to PDF on request for any app using this framework? Are you and Raghu on the same page regarding this topic (ie: Raghu's PDF conversion === yours?)?

**Comment by GordonSmith** [comment]
What I am saying is that for a given ramps dashboard there will be a server service to fetch it as a PDF.
In the UK solution the request goes to a service, the service then opens the URL in PhantomJS, saves it as a PDF and then returns that.  

(Its basically the same as the user opening the page in Chrome and clicking "save as pdf...")

**Comment by GordonSmith** [comment]
Closing this issue as its not a Viz Framework issue (as its a server side thing).
