### ISSUE TITLE
Table rendered in 1.10.0 brach is not scrollable

### ISSUE THREAD

**Issue by RajalakshmiElumalaiCts** [hpcc-systems/Visualization#1208]
![table](https://cloud.githubusercontent.com/assets/5885849/11243100/087fd1dc-8e2c-11e5-9941-df78bdcb77ab.jpg)

**Comment by dtsnell4** [comment]
@GordonSmith this should have been fixed in via this issue https://github.com/hpcc-systems/Visualization/issues/1165 with this PR https://github.com/hpcc-systems/Visualization/pull/1104

Is there somewhere I can see this happen?  Are we sure it is using the latest version of 1.10?  Its working here http://rawgit.com/hpcc-systems/Visualization/candidate-1.10.0/demos/graph/index.html

![capture](https://cloud.githubusercontent.com/assets/4304235/11244921/2bc33858-8dde-11e5-93d1-d83c7c1c91cf.PNG)

**Comment by GordonSmith** [comment]
IE?

**Comment by dtsnell4** [comment]
Nope, still scrolls in IE.

**Comment by RajalakshmiElumalaiCts** [comment]
Have taken latest 1.10.0 branch code again.Now could see the scroll bar.

**Comment by dtsnell4** [comment]
OK, great thank you!

**Comment by GordonSmith** [comment]
This has been resolved when ZN_GRAPH got rebased onto candidate 1.10.0
