### ISSUE TITLE
Return a message if JSON response from ROXIE is empty

### ISSUE THREAD

**Issue by dineshshetye** [hpcc-systems/Visualization#1554]
If the ROXIE service associated with a widget is not able to return data (due to whatever reason, one reason is if the generic account password used in DSP for roxie communication has expired ), the JSON response is empty json blob. We need Viz to pass back a message to DSP so it doesn't just look like a viz glitch.

**Comment by GordonSmith** [comment]
Shouldn't the proxy layer handle this?

**Comment by jchambers-ln** [comment]
https://github.com/hpcc-systems/DSP/issues/1017 depends on this (putting it here so we can see the notice in the ticket when this closes.

If the proxy handles it then we need a standard Error response that it can pass to the marshaller and that error be displayed. However in a direct to roxie situation I think the marshaller should have a default error notice.

We also need to surface 500 errors if the user (service or otherwise) authentication fails on Roxie.

**Comment by GordonSmith** [comment]
If I get an exception from roxie I will display that - 500 is trickier because I am using jsonp (not 100% sure I can even catch it)...

**Comment by GordonSmith** [comment]
The viz framework will display an error msg, after it has timed out (60secs)

**Comment by GordonSmith** [comment]
@jchambers-ln Can you point me to a server I can reproduce this with?

**Comment by jchambers-ln** [comment]
I would set one up and then delete the roxie service or something... it usually occurs if the service hasn't finished deploying or other reasons... I don't have a specific one where it occurs.

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
