### ISSUE TITLE
Add pivot table widget (Orb.js)

### ISSUE THREAD

**Issue by jpellock** [hpcc-systems/Visualization#1908]
We'd like to create a pivot table widget leveraging Orb.js. 
http://orbjs.net/

You should be able to select fields from your data to populate on either rows or columns as attributes or data. You should also be able to do the following: 
- check if you want sub totals and/or grand totals visible
- check if you want attributes collasped or expanded
- check if the toolbar should be visible
- populate height/width
- for attributes
  - enter a caption
  - specify sort order
- for data
  - enter a caption
  - specify sort order
  - specify an aggregation functions (sum, avg, ...)
  - specify a format utilizing d3.format
- specify a _theme_

@mounicarachakonda 
@yangxulexis

**Comment by GordonSmith** [comment]
Boilerplate environment here:  https://github.com/GordonSmith/Visualization/tree/ORB_TEST

**Comment by yangxulexis** [comment]
Original orb.js library has a "disadvantage" that table is not "responsive". The user experience would be unfavorable when it was shown on small screen. To improve that, I guess we are going to use Bootstrap/CSS (or anything else?). The issue is that we have to change some code in original orb.js library, which, I think, is not the way we are supposed to do. Maybe we can add supplemental bootstrap/css in our local orb folder. But in the future, we would extensively re-write the orb.js library to achieve diverse functionalities. Would that be a problem if we could not modify the original orb.js library in bower_components?

**Comment by GordonSmith** [comment]
Nothing preventing us from forking the current Orb implementation and improving it - we can issue pull requests back to the original project, but use our forked version in the interim?

**Comment by yangxulexis** [comment]
The orb.js project was discontinued in 2015. Pull request was never taken care of, which means any update  would not be shown up on public repo unless we make our own one...

**Comment by xiahx** [comment]
What's in dermatology now for the pivot table is to utilize "properties" to get the field. @GordonSmith Gordon, you have suggested @yangxulexis to pre-load all of the columns in dermatology. We (FIDO team) have discussed it internally and don't think it's necessary given that it's very likely we'll have lots of columns in a given source file. "Pre-loading" all of them will make the "field" section really crowded. Also we have issues on responsiveness that when there're lots of rows and columns in pivot table, users can't see all of them no matter how we scroll the screen.  That's why we think keeping it in "properties" is a better choice. But we are not sure how this will turn out once pushed into DSP. 

In current DSP, when a dashboard designer selects a widget ( for example: table widget) and specified data source, all of the available fields show up on the left hand section on the screen to allow user to drag and drop selected columns/fields to be used in the widget.

So for this new pivot table widget, will it be the same way? 

Thank you

**Comment by dabayliss** [comment]
@GordonSmith hope you don't mind me interjecting to a viz thread - but IMO there is a HIPIE interaction here ...

@xiahx I almost exactly 50% agree with you. It is a little more complex to 'pre-think' - but we really need to think of this as a "two-stage" process for a DSP user USING the pivot table.

Stage 1: The DSP user selects those fields from the source file that are available for pivoting at run time. The source file might have thousands of fields but for a given view the DSP user will select 2->6. This stage corresponds to "build time" - HIPIE will build keys based upon this selection

Stage 2: which COULD be build time but could be RUN time - two of those columns are selected to build the pivot table. If there are 6 fields selected in stage 1 then there are 30 different pivot tables that could be chosen at this point. NONE of these selections require HIPIE to rebuild.

Obviously you can say: "that is too complex" - but it saves HIPIE a TON or work and it saves a ton of index building - you get 30 dashboards for the price of one.

Now - as you say - if one goes to the other extreme and put 1000 fields into the widget you have millions of dashboards you can build; but it is also going to be dog-slow to execute

HTH

**Comment by yangxulexis** [comment]
Have changed back to previous version---would not show any field when enter the web page.
@xiahx @GordonSmith

**Comment by GordonSmith** [comment]
Its been added.
