### ISSUE TITLE
am_line chart null data charted 

### ISSUE THREAD

**Issue by jchambers-ln** [hpcc-systems/Visualization#2013]
Null data is charted as zero point in "am_line" chart. "Line" chart handles it correctly.

Reference: hpcc-systems/DSP#977

if the data set had points with no data, the am_line would draw a line down to zero while the regular line would interpolate

**Comment by hamiltwp** [comment]
This happens when you plot a left outer join with no right-hand side record http://10.173.147.1:8010/?Wuid=W20160919-152334&Widget=WUDetailsWidget#  for example 
Interpolating, or leaving a gap makes sense, but inserting a zero point does not reflect the data:
![line2](https://cloud.githubusercontent.com/assets/6495693/18646154/585f67ba-7e7e-11e6-8ead-e6aa2402fe1d.jpg)
![line3](https://cloud.githubusercontent.com/assets/6495693/18646156/5a511a00-7e7e-11e6-9882-ef0c01295f77.jpg)


![line1](https://cloud.githubusercontent.com/assets/6495693/18646131/3d1e6bae-7e7e-11e6-98a5-ff98e7e23e90.jpg)

**Comment by GordonSmith** [comment]
Closed "timed-out", please reopen if needed.
