### ISSUE TITLE
Ability to remove fields from CSV export in dashboards

### ISSUE THREAD

**Issue by juliedobro** [hpcc-systems/Visualization#2492]
We would like the ability to remove fields from the CSV download option in the dashboard. (example JIRA tickets BIS-389 and BIS-236)
Currently we can hide fields that we need from displaying in dashboards table but in addition to being able to hide them in the dashboards we would also like the ability to remove them from being downloaded in the CSV table.

**Comment by GordonSmith** [comment]
@juliedobro are you saying that we should simply download all fields that aren't specifically hidden?  (instead of all fields like we are currently)

IOW You only have the option to hide a field, you won't have the option to hide it in the table, but not have it hidden in the download (and vice versa - you can't hide it in the download and have it visible in the table).

**Comment by juliedobro** [comment]
I agree with you. You would have the option not to download a field that's hidden in the dashboard table; however, I think it should be an option that defaults to always download all the fields (regardless of their visibility status in the dashboard) and if a field is hidden in the dashboard then you can also 'hide' it from the download.
