### ISSUE TITLE
IE11 Issue?

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#3061]
Looks like there might be an IE 11 issue:
![image](https://user-images.githubusercontent.com/966863/50595475-61321200-0e98-11e9-8e76-e162063b7e30.png)

**Comment by jbrundage** [comment]
This is affecting any widget rendered in a ChartPanel in IE11 and it's caused by differences in `flex-basis` behavior.
Changing the `60%` on this line to `auto` resolves the horizontal alignment issue, but IE11 doesn't resize the `center` and `rhs` containers when hiding/showing the legend.
https://github.com/hpcc-systems/Visualization/blob/master/packages/layout/src/Border2.css#L9

I'm still looking for a css-only solution.
