### ISSUE TITLE
ChartPanel with Column Bars Hovering

### ISSUE THREAD

**Issue by lucashby** [hpcc-systems/Visualization#3126]
If you run this example:

```
import { Column } from "@hpcc-js/chart";
import { ChartPanel } from "@hpcc-js/layout";

const cp = new ChartPanel()
    .widget(new Column())
    .columns(["Subject", "Year 1", "Year 2", "Year 3"])
    .data([
        ["Jan", 1, 6, 21],
		["Feb", 0, 6, 17],
		["Mar", 0, 1, 10],
		["Apr", 0, 3, 6],
		["May", 1, 2, 13]
    ])
    .target("target")
    .title("Exam Results 2008->10")
    .legendVisible(true)
    .render();
```

you can observe the behavior.  Basically the bars are rendering in a way that is hovering over the x-axis.  Not sure why.  Please fix ASAP.

Screenshot:

![image](https://user-images.githubusercontent.com/938632/52814816-1399ef00-306b-11e9-8be4-675e982e8b17.png)

**Comment by GordonSmith** [comment]
@jbrundage - I suspect this is related to the "zero line" modifications?

**Comment by jbrundage** [comment]
I've finally found the source of the issue. At first it seemed to happen randomly, but it turns out that it happens when the top yAxis tick label slightly extends beyond the top of the chart:
![image](https://user-images.githubusercontent.com/1891935/52876758-232a3e00-3126-11e9-8de8-f7979be43849.png)
The XYAxis layers just need to be shifted by that overlap amount as well. I'll issue a pull request shortly.
