### ISSUE TITLE
Add "simple selection" support to Google Charts

### ISSUE THREAD

**Issue by GordonSmith** [hpcc-systems/Visualization#769]

**Comment by dtsnell4** [comment]
@GordonSmith 

Matt, J and I had a conversation last week about these issues with the SimpleSelection support.  Matt said he had a conversation with you where you were going to be doing some updating to the Utility widget and we should hold off on these.  That said I only have a few low priority items left on my list so I decided to look into this yesterday.

It seems doing this with the Google charts will be very tricky, if possible.  Getting the data of the element is easy via the built in getSelection() method.  However SimpleSelection needs the element that was clicked on, but the google charts have no way of getting the element, in fact the element that was clicked (a rect) is removed from the dom completely and replaced with a (g) element that then has several child rects that are superimposed to give the column/bar/etc. its "selected" appearance.  Even though I can get the element that was clicked with d3.event.target, that element is immediately removed and replaced with new elements. As of right now I',m mot sure how would get these new elements (if that's even the right hing to do), as nothing in the google charts have any identifying id, class etc.  It may be possible, but will take some time and I'm not sure if I should be spending time on it right now.  I'm going to wait for your input before continuing.

**Comment by GordonSmith** [comment]
I thought google supported "simple selection" out of the box and the click event would just need to pass true/false for new selected param on the click.  The only reason you would need the d3 element would be for highlighting the selected item?

**Comment by dtsnell4** [comment]
I suppose it does and I guess my problem is I don't understand the definition of "simple selection" in the context of the framework.  Based on the title of the issue and the conversation with Matt and J, I was under the impression I was supposed to implement SimpleSelection() in the Utility widget.  You are correct, Google has its own "select" and "click" methods and highlights its own selections internally.

So in order to understand better, could you elaborate on "the click event would just need to pass true/false for new selected param on the click"?  I'm not really sure what that means exactly.

**Comment by GordonSmith** [comment]
Rhe click event should pass (row, col, selected) on click:
row:  this is the entire data row
col: this would be the column ID
selected: true/false depending if the click selected or deselected it.
