### ISSUE TITLE
Table click.selectionBag can cause multiple selections

### ISSUE THREAD

**Issue by jbrundage** [hpcc-systems/Visualization#833]
When a row is clicked it will become selected. If any other rows contain the same content as the clicked row, they will also be selected.

**Comment by dtsnell4** [comment]
@GordonSmith @jbrundage 

I'm not sure if this is a bug, or just an anomaly because of how we were displaying the test data for the "large" table.  At one point Gordon added a line to the test data that concatenates the the data array several times, just to make the table really big to test the fixed header and column.  It is the fact that there are rows with _identical_ data that are causing this issue.  I don't know if this is a real life scenario that we need to be concerned with, but if it is, we will need to change how we store selected data in the selection bag.  In fact the latest version of test date in candidate 1.8.0 does not do this concatenation any more, so the bug is no longer there.   

Currently the Table widget's _createSelectionObject() selects all "tr" nodes that have .__data__ property equivalent to the selected row, and then selectionBag adds the "selected" class to them. Since we have two rows with identical data, they both get the selected class and appear highlighted.  

I'm not sure what to do about this scenario without changing how the selectionBag works, and I'm not sure that is within the scope of this issue.  If it is, I could use some suggestions about how we want to restructure the selection data.

**Comment by GordonSmith** [comment]
You are correct it is due to the duplicate rows, I would consider it a bug...

**Comment by dtsnell4** [comment]
@GordonSmith Ok, in that case do you have any suggestions as to how I could go about changing the Table's selection object to make identical rows unique so the selectionBag can tell the difference?  My first thought would be to index the rows but sorting by different columns would invalidate that index.  I'm kind of at a loss as to how to accomplish this.

**Comment by GordonSmith** [comment]
Like Matt said I would wait a little bit - I have a new replacement for _data and it may be able to manage some of this...

**Comment by dtsnell4** [comment]
OK, will do

**Comment by GordonSmith** [comment]
I believe this has been resolved.
